---
version: '3'

services:
  openldap:
    restart: "always"
    image: bitnami/openldap:2.6.6
    ports:
      - 1389:1389
    environment:
      LDAP_ADMIN_USERNAME: ${LDAP_ADMIN_USERNAME:-admin}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-Admin123}
      LDAP_CONFIG_ADMIN_ENABLED: ${LDAP_CONFIG_ADMIN_ENABLED:-yes}
      LDAP_CONFIG_ADMIN_USERNAME: ${LDAP_CONFIG_ADMIN_USERNAME:-configadmin}
      LDAP_CONFIG_ADMIN_PASSWORD: ${LDAP_CONFIG_ADMIN_PASSWORD:-Configadmin123}
      LDAP_ALLOW_ANON_BINDING: no
    healthcheck:
      test: ldapsearch -H 'ldap://127.0.0.1:1389' >/dev/null; if [[ $$? == 53 ]]; then echo 0; else echo 1; fi
    volumes:
      - database-ldap:/bitnami/openldap/data
      - config-ldap:/bitnami/openldap/slapd.d

  backup:
    image: openmrsinfra/cron-backup:latest
    depends_on:
      - openldap
    volumes:
      - config-ldap:/ldap_config_data
      - database-ldap:/ldap_database_data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/ldap_config_data:ldap_config,/ldap_database_data:ldap_database
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  database-ldap:
  config-ldap:
