---
version: '3.5'

services:
  openldap:
    restart: "always"
    image: osixia/openldap:1.5.0
    command: "--copy-service"
    ports:
      - 3389:389
    environment:
      LDAP_ORGANISATION: OpenMRS
      LDAP_DOMAIN: openmrs.org
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config}
      LDAP_TLS: ${LDAP_TLS:-false}
      LDAP_LOG_LEVEL: 0
    healthcheck:
      test: "exit 0"
    volumes:
      - config-ldap:/etc/ldap/slapd.d
      - database-ldap:/var/lib/ldap
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom

      # Only adds test data locally
      - ./test-data/70-test-users.ldif:${TEST_DATA_DIR-/container/service/slapd/assets/config/bootstrap/ldif/custom/}70-test-users.ldif
      - ./test-data/80-test-groups.ldif:${TEST_DATA_DIR-/container/service/slapd/assets/config/bootstrap/ldif/custom/}80-test-groups.ldif

volumes:
  config-ldap:
  database-ldap:
