---
version: '3'

services:
  openldap:
    restart: "always"
    image: osixia/openldap:1.2.4
    container_name: openldap       # used by letsencrypt hook
    command: "--copy-service"
    ports:
      - 636:636
    environment:
      LDAP_ORGANISATION: OpenMRS
      LDAP_DOMAIN: ${LDAP_DOMAIN:-openmrs.org}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config}
      LDAP_TLS_CRT_FILENAME: ${LDAP_TLS_CRT_FILENAME:-ldap.crt}
      LDAP_TLS_KEY_FILENAME: ${LDAP_TLS_KEY_FILENAME:-ldap.key}
      LDAP_TLS_CA_CRT_FILENAME: ${LDAP_TLS_CA_CRT_FILENAME:-ca.crt}
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_LOG_LEVEL: 0
    healthcheck:
      test: "ldapsearch -H ldap://localhost -D 'cn=admin,dc=openmrs,dc=org' -w $$LDAP_ADMIN_PASSWORD -b 'ou=system,dc=openmrs,dc=org' || exit 1"
    volumes:
      - config-ldap:/etc/ldap/slapd.d
      - database-ldap:/var/lib/ldap
      - ${CERTS_DIR-./certs}:/container/service/slapd/assets/certs/

  backup:
    image: openmrsinfra/cron-backup:latest
    depends_on:
      - openldap
    volumes:
      - config-ldap:/ldap_config_data
      - database-ldap:/ldap_database_data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/ldap_config_data:ldap_config,/ldap_database_data:ldap_database
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  config-ldap:
  database-ldap:
