version: '3'

services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Postgres123}
    healthcheck:
      test: "pg_isready -U postgres"
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
    image: openmrsinfra/openmrs-id-keycloak:nightly
    depends_on:
      - db
    environment:
      - KC_HOSTNAME=${KC_HOSTNAME:-localhost}
      - KC_DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER:-postgres}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-Postgres123}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-Admin123}
      - KC_PROXY=${KC_PROXY:-edge}
    healthcheck:
      test: curl --silent --fail --insecure https://localhost:8080/health/ || exit 1
    restart: "always"
    ports:
      - "8080:8080"
  postfix:
    image: openmrsinfra/openmrs-id-postfix:nightly
    ports:
      - "389:389" # Make LDAP running on host available to postfix
    environment:
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-username}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD:-password}
      - LDAP_HOST=${LDAP_HOST:-localhost}
      - LDAP_PORT=${LDAP_PORT:-389}
volumes:
  postgres_data:
    driver: local

